name: Generate Marp Slides

# Required permissions for GitHub Actions to write to repository
permissions:
  contents: write
  pull-requests: write

on:
  push:
    branches: [ main ]
    paths:
      - 'doc/02_requirements_definition/rdd.md'
  pull_request:
    branches: [ main ]
    paths:
      - 'doc/02_requirements_definition/rdd.md'

jobs:
  generate-slides:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Create output directory
      run: mkdir -p doc/99_slide_pdf
      
    - name: Generate PDF slides with Marp
      run: npm run marp
      
    - name: Generate HTML slides with Marp
      run: npm run marp:html
      
    - name: Commit and push generated slides
      if: github.event_name == 'push'
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: '🎨 Auto-generate slides from rdd.md [skip ci]'
        file_pattern: 'doc/99_slide_pdf/*'
        commit_user_name: 'GitHub Action'
        commit_user_email: 'action@github.com'
        skip_dirty_check: false
        
    - name: Upload slides as artifacts
      uses: actions/upload-artifact@v4
      with:
        name: generated-slides
        path: doc/99_slide_pdf/
        retention-days: 30
